config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :sessions => 'users/sessions', registrations: "registrations"}
resources :users, :only => [:index, :show] do
  member do
    get :following, :followers
  end
end
  resources :conversations do
    member do
      get 'ready'
    end
    resources :messages, :only => [:index, :create]
  end

  resources :guests, only: [:create]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:index, :create]
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/video',   to: 'static_pages#video',   via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
	
	has_many :messages, dependent: :destroy
	
	#validates_uniqueness_of :sender_id, :scope => :recipient_id

	# status: waiting, ready, close
	enum status: {waiting: 0, ready: 1, close: 2}
	scope :involving, -> (user) do
	  where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
	end
	
	scope :between, -> (sender_id,recipient_id) do
	  where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
	end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @your_id = params[:sender_id]
    @conversation = Conversation.new
    @messages = @conversation.messages
  end

  def ready
    @conversation = Conversation.find_by(id: params[:id])
    if @conversation.waiting?
      @conversation.ready!
    end
    render :nothing => true
  end

  def create
    #Guest作成
    user = current_or_guest_user
    @matching_id = user.id.to_s
    # response = Pusher.get('/channels/' + 'user_' + guest.id.to_s)
    # if response[:occupied]
    #   Pusher['user_' + guest.id.to_s].trigger('cancelled', { })
    # end
    challenge_response(user)
  end
 
  def show
    @your_id = params[:your_id]
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
    respond_to do |format|
      format.js
      format.html
    end
  end
 
  private
  def guest_params
    params.require(:guest).permit(:username, :sex)
  end
  def challenge_response(user)
    #search_sex = guest.sex === "M" ? "F" : "M"
    border_time = Time.zone.now - 10
    @conversation = Conversation.where("recipient_id IS ? AND status = 1",nil).first

    if @conversation.nil? then
      # create conversation
      old_conversation = Conversation.where("sender_id = ? AND recipient_id IS ? AND status = 0",user.id,nil).first
      if old_conversation
        old_conversation.destroy
        challenge_response(user)
      else
        @conversation = Conversation.create!(sender_id: user.id,recipient_id: nil, status: 0)
        redirect_to conversation_path(:id => @conversation.id, :your_id => user.id) and return
      end
    else
      waiting_user = User.find_by(id: @conversation.sender_id)
      if waiting_user.id === user.id
        @conversation.destroy
      else
        response = Pusher.get('/channels/' + 'chat_' + waiting_user.id.to_s)
        event_waiting = response[:occupied]
        if event_waiting
          # join
          Pusher['chat_' + @conversation.sender_id.to_s].trigger('starting', {
              room_id: @conversation.id,
              your_id: guest.id
          })
          @conversation.update(recipient_id:user.id,status: 2)
          redirect_to :controller=>"conversations", :action => "show",
                      :id => @conversation.id, :your_id => user.id and return
        else
          @conversation.destroy
          waiting_user.destroy
        end
      end
      challenge_response(guest)
    end
  end

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
 
  def interlocutor(conversation)
    Guest.find_by(userid: session[:session_id]).id == conversation.recipient_id ? conversation.sender_id : conversation.recipient_id
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def interlocutor(conversation)
    Guest.find_by(userid: session[:matching_id]).id == conversation.recipient_id ? conversation.sender_id : conversation.recipient_id
  end
end

app/views/conversations/_chat.html.erb
  <div class="chat-window" data-userid="<%=	@your_id  %>">
    <div class="chat-messages">
      <ol class="chat-messages-list">
        <li class="chat-message chat-message-friend">
          <div class="chat-message-bubble">
            waiting
          </div>
        </li>
        <%= render @messages %>
      </ol>
    </div>
    <div class="chat-input-bar">
      <div class="chat-info-container">

      </div>
      <div class="chat-effect-container">
        <div class="chat-effect-bar"></div>
      </div>
      <div class="chat-input-wrapper">
        <%= render "input" %>
      </div>
    </div>
  </div>
</div>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="800">
  <defs>
    <filter id="goo">
      <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
      <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo" />
      <feComposite in="SourceGraphic" in2="goo" />
    </filter>
  </defs>
</svg>

app/views/conversations/_input.html.erb
<button class="chat-input-tool">
  <i class="icon icon-camera"></i>
</button>
<div class="chat-input" contenteditable></div>
<button class="chat-send" data-cid="<%= @conversation.id %>" data-rid="<%= @reciever %>">
  <i class="fa fa-paper-plane"></i>
</button>

app/views/conversations/index.html.erb
<%= render 'chat' %>

app/views/conversations/new.html.erb
<%= render 'chat' %>

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

  </div>
  <div class="chatboxoptions" data-userid="<%= @your_id  %>">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], url: conversation_messages_path(@conversation, @message,your_id: @your_id),:remote => true) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
      <%= f.submit %>
  <% end %>
</div>

app/views/conversations/show.js.erb
$('.chat-input-wrapper').html("<%= escape_javascript(render 'input') %>")
chat_start()